name: Go Test Run

on: [push]

# When a new revision is pushed to a PR, cancel all in-progress CI runs for that
# PR. See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  go-test:
    name: Go Test (${{ matrix.os }})
    runs-on: ${{ matrix.run }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux
            run: ubuntu-22.04
          # MacOS is disabled due to the high cost multiplier on GH Actions.
          #- os: darwin
          #  run: macos-12
          # Windows not allowed currently because of line-ending conversion issues.
          #- os: windows
          #  run: windows-2022
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Go 1.16
        uses: actions/setup-go@v3
        with:
          go-version: '1.16'

      - name: Unit Test Golang
        run: go test ./...
        timeout-minutes: 30

      - name: Test Race
        run: go test -race ./...
        timeout-minutes: 30

      - name: Flakey Test Ordering
        run: go test -count 25 ./...
        timeout-minutes: 30
